name:                HaskellExercises04
version:             0.1.0.0
github:              "dalvescb/HaskellExercises04"
license:             BSD3
author:              "Curtis D'Alves"
maintainer:          "curtis.dalves@gamil.com"
copyright:           "(c) Curtis D'Alves 2020"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dalvescb/HaskellExercises04#readme>

dependencies:
- base >= 4.7 && < 5
- QuickCheck
- hspec

library:
  source-dirs: src

executables:
  HaskellExercises04-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellExercises04

tests:
  HaskellExercises04-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellExercises04
